### PR TITLE
Fixed migration for Literal Datatypes

### LINKED ISSUE #382: [BUG] Validation fails for value type bamm:curie for  bamm-c:UnitReference characteristic in SAMM-CLI 2.2.2
**Describe the bug**
Trying to validate a model with the following snippet with bamm-cli-2.1.3 is correct but with  SAMM-CLI 2.2.2 not.
 
```
:measurementUnit a bamm:Property;
    bamm:preferredName "Measurement Unit"@en;
    bamm:description "Unit of measurement for the quantity of serialized objects."@en;
    bamm:characteristic bamm-c:UnitReference;
    bamm:exampleValue "kW"^^bamm:curie.
```
 
which validated. With the new SAMM-CLI the following validation error appears:
https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.single_level_bom_as_specified/1.0.0

 ```
java -jar samm-cli-2.2.2.jar  aspect io.catenax.single_level_bom_as_specified/1.0.0/SingleLevelBomAsSpecified.ttl validate
```

```
Semantic violations were found:



> :measurementUnit :

  The datatype 'bamm:curie' of the exampleValue neither matches nor can be cast to the Property's ':measurementUnit' Characteristic's dataType.
```
 
switching to the SAMM 2.0.0 meta model resolves the problem. However, this is not possible for released models.

**Where**
SAMM-CLI 2.2.2

**Screenshots**
na

**Additional context**

### PR DESCRIPTION
**Pull request by ysrbo**
Fixes #382

### CODE REVIEW

**Review by atextor — APPROVED** [review]
LGTM!

File: core/esmf-aspect-meta-model-version-migrator/src/main/java/org/eclipse/esmf/aspectmodel/versionupdate/migrator/BammUriRewriter.java [hunk 1]
```diff
@@ -65,7 +61,7 @@ protected Map<String, String> buildReplacementPrefixMap( final Model sourceModel
       // The mapping of the URNs of the legacy BAMM Aspect Meta model to their corresponding SAMM counterparts
       return Map.of(
             "urn:bamm:io.openmanufacturing:meta-model:" + bammVersion.versionString() + "#", targetPrefixes.get( "samm" ),
-            "urn:bamm:io.openmanufacturing:characteristic:" + bammVersion.versionString() + "#", targetPrefixes.get( SAMM_C_PREFIX ),
+            "urn:bamm:io.openmanufacturing:characteristic: " + bammVersion.versionString() + "#", targetPrefixes.get( SAMM_C_PREFIX ),
```
Comment (atextor) [inline core/esmf-aspect-meta-model-version-migrator/src/main/java/org/eclipse/esmf/aspectmodel/versionupdate/migrator/BammUriRewriter.java:64]: I think this change is a regression, please remove this space

**Review by atextor — CHANGES_REQUESTED** [review]
