### PR TITLE
Fix broken samm-cli exectuable jar

### LINKED ISSUE #911: [BUG] samm-cli: aspect validate command broken for executable .jar
**How: List of performed steps**
This is a follow-up to #906: The reported problem not only exists with the samm-cli binary but also with the executable .jar

**What: Actual result vs expected result**
See linked issue

**Where: (e.g. component, version, url, your system info)**
samm-cli 2.14.1, executable .jar version

### PR DESCRIPTION
**Pull request by atextor**
## Description

Fixes the `aspect validate` command in the executable .jar for samm-cli

Fixes #911 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: tools/samm-cli/src/test/java/org/eclipse/esmf/SammCliIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
+/*
+ * Copyright (c) 2023 Robert Bosch Manufacturing Solutions GmbH
```
Comment (Yauhenikapl) [inline tools/samm-cli/src/test/java/org/eclipse/esmf/SammCliIntegrationTest.java]: 2026

**Review by Yauhenikapl — APPROVED** [review]
