### PR TITLE
Fix evaluation of sh:node in sh:PropertyShapes

### LINKED ISSUE #361: [BUG] sh:node inside of property shapes is not correctly evaluated
**Describe the bug**
In the SHACL validator of the esmf-aspect-model-validator module, using sh:node inside a property shape is not validated correctly. The node shape that is referred to by sh:node should be evaluated against the value node(s) that are reachable via the property shape's sh:path attribute.

**Where**
esmf-aspect-model-validator, ShaclValidator and ShapeLoader

### PR DESCRIPTION
**Pull request by atextor**
Fixes #361

### CODE REVIEW

File: core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/constraint/NodeConstraint.java [hunk 1]
```diff
@@ -14,20 +14,30 @@
...
 import org.eclipse.esmf.aspectmodel.shacl.violation.EvaluationContext;
 import org.eclipse.esmf.aspectmodel.shacl.violation.Violation;
 
 /**
  * Implements <a href="https://www.w3.org/TR/shacl/#NodeConstraintComponent">sh:node</a>
- * @param shape the node shape this sh:node refers to
+ * @param targetShape the node shape this sh:node refers to
  */
-public record NodeConstraint(Shape.Node shape) implements Constraint {
+public record NodeConstraint(Optional<Path> path, Shape.Node targetShape) implements Constraint {
```
Comment (KobOp) [inline core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/constraint/NodeConstraint.java:30]: Should the Optional parameter be placed after the mandatory ones?

File: core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/RustLikeFormatter.java [hunk 2]
```diff
@@ -231,6 +231,12 @@ private boolean formatNode( final RDFNode node ) {
          if ( node.asNode().equals( NodeConst.nodeRDFType ) ) {
             spacedIfPossible( "a " );
```
Comment (KobOp) [inline core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/RustLikeFormatter.java:232]: Is a space behind 'a' intended?

File: core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/constraint/NodeConstraint.java (hunk 1 above)
Comment (atextor) [reply core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/constraint/NodeConstraint.java]: Nice catch, you are right

File: core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/RustLikeFormatter.java (hunk 2 above)
Comment (atextor) [reply core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/RustLikeFormatter.java:232]: In this case yes, because there will always be a space after the 'a ' (= rdf:type) token when formatting, because it can only appear as the predicate in a triple and is followed by some object.

**Review by Yauhenikapl — APPROVED** [review]

File: core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/RustLikeFormatter.java [hunk 3]
```diff
@@ -231,6 +231,12 @@ private boolean formatNode( final RDFNode node ) {
...
          }
+         if ( node.asNode().equals( NodeConst.nodeTrue ) ) {
```
Comment (MelleD) [inline core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/RustLikeFormatter.java:234]: I would recommend to use the constant first 
NodeConst.nodeTrue.equals(node.asNode())

File: core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/ShaclValidator.java [hunk 4]
```diff
@@ -128,7 +125,8 @@ public List<Violation> validateModel( final VersionedModel model ) {
    private Map<Resource, List<Shape.Node>> findSparqlTargets( final Model model ) {
       final Map<Resource, List<Shape.Node>> resourceShapes = new HashMap<>();
       for ( final Shape.Node shape : targetSparqlShapes() ) {
-         final List<Resource> shapeTargets = querySparqlTargets( model, shape.attributes().targetSparql().get() );
+         final List<Resource> shapeTargets = querySparqlTargets( model, shape.attributes().targetSparql().orElseThrow( () ->
+               new RuntimeException( "SPARQL node shape is missing a target SPARQL expression" ) ) );
```
Comment (MelleD) [inline core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/shacl/ShaclValidator.java:129]: I would not throw a RuntimeException. Maybe a own exception or Illegal exception?

**Review by MelleD — APPROVED** [review]
