### PR TITLE
the bugfix multiple instantiation abstract entities

### LINKED ISSUE #343: [BUG] Multiple instantiation of Entities when loading Aspect Models
**Describe the bug**
When an Aspect Model includes two Entities that extend the same ComplexType (it does not matter if the extended ComplexType is an `Entity` or an `AbstractEntity`), the two Entities will have references to different instances of `ComplexType`. If the `ComplexType` has child elements, they will also be instantiated twice.
Instead, for both Entities, the attribute _extends should refer to the same `ComplexType`.

**Where**
esmf-aspect-meta-model-java

### PR DESCRIPTION
**Pull request by ysrbo**
PR fixes duplicated instantiation of Abstract entities when loading aspect models

Fixes #343

### CODE REVIEW

File: core/esmf-aspect-meta-model-java/src/test/java/org/eclipse/esmf/metamodel/loader/AspectModelLoaderTest.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
+/*
+ * Copyright (c) 2021 Robert Bosch Manufacturing Solutions GmbH
```
Comment (atextor) [inline core/esmf-aspect-meta-model-java/src/test/java/org/eclipse/esmf/metamodel/loader/AspectModelLoaderTest.java:2]: 2023

File: core/esmf-test-aspect-models/src/main/resources/valid/samm_1_0_0/org.eclipse.esmf.test/1.0.0/AspectWithMultipleEntitiesSameExtend.ttl [hunk 2]
```diff
@@ -0,0 +1,60 @@
+#
+# Copyright (c) 2021 Robert Bosch Manufacturing Solutions GmbH
```
Comment (atextor) [inline core/esmf-test-aspect-models/src/main/resources/valid/samm_1_0_0/org.eclipse.esmf.test/1.0.0/AspectWithMultipleEntitiesSameExtend.ttl:2]: 2023

**Review by atextor — CHANGES_REQUESTED** [review]
