### PR TITLE
Fix no conversion of uppercase strings

### LINKED ISSUE #620: [BUG] Enum Generator produces snake_case enums instead of UPPERCASE
The Enum Generator currently generates enums by converting it to snake_case values also when the complete string is uppercase. For example, the string "ABC" is transformed into "A_B_C". 
This behavior is not as expected. 
The generated enum should preserve the original string format, such that "ABC" remains "ABC".

### PR DESCRIPTION
**Pull request by MelleD**
## Description

Fix no conversion of uppercase strings

Fixes #620

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: core/esmf-aspect-model-java-generator/src/test/java/org/eclipse/esmf/aspectmodel/java/AspectModelJavaUtilTest.java [hunk 1]
```diff
@@ -43,4 +48,25 @@ public boolean generatedEnumKeysAreValidJavaIdentifiers( @ForAll( "anyValidTypeV
       final String result = AspectModelJavaUtil.generateEnumKey( tuple.get2() );
       return isValidJavaIdentifier( result );
    }
+
+   @ParameterizedTest
+   @MethodSource
+   void generatedEnumKeysAreExpectedEnumNames( final String enumValueName, final String expectedEnumValueName ) {
+      final String result = AspectModelJavaUtil.toConstant( enumValueName );
+      Assertions.assertThat( result ).isEqualTo( expectedEnumValueName );
```
Comment (atextor) [inline core/esmf-aspect-model-java-generator/src/test/java/org/eclipse/esmf/aspectmodel/java/AspectModelJavaUtilTest.java:56]: Please add a static import for `assertThat()`

**Review by atextor — CHANGES_REQUESTED** [review]

**Review by atextor — APPROVED** [review]
LGTM!
