### PR TITLE
Fix problem with the resolution of the old BAMM 1.0.0 models.

### LINKED ISSUE #363: [BUG] SAMM-CLI v2.2.1 assumes wrong default namespace for BAMM2.0.0 models
**Describe the bug**
I have a model

```
@prefix bamm: <urn:bamm:io.openmanufacturing:meta-model:2.0.0#>.
@prefix bamm-c: <urn:bamm:io.openmanufacturing:characteristic:2.0.0#>.
@prefix bamm-e: <urn:bamm:io.openmanufacturing:entity:2.0.0#>.
@prefix unit: <urn:bamm:io.openmanufacturing:unit:2.0.0#>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix : <urn:bamm:io.catenax.example_aspect:1.0.0#>.

:ExampleAspect a bamm:Aspect;
    bamm:properties (:property1);
    bamm:operations ();
    bamm:events ().
:property1 a bamm:Property;
    bamm:characteristic :Characteristic1.
:Characteristic1 a bamm:Characteristic;
    bamm:dataType xsd:string.
```

when I run the SAMM CLI v2.2.1 to validate the model
```
java -jar samm-cli-2.2.1.jar  aspect io.catenax.example_aspect/1.0.0/ExampleAspect.ttl validate
```
It does not validate the model but returns the error message
```
Validation failed:
Resolution strategy returned a model which does not contain element definition for urn:samm:io.catenax.example_aspect:1.0.0#ExampleAspect
```
As one can see it assumes another default namespace 
```
urn:samm:io.catenax.example_aspect:1.0.0#ExampleAspect
```
as the one provided
```
urn:bamm:io.catenax.example_aspect:1.0.0#ExampleAspect
```

This prevents using the SAMM-CLI and SDK for already existing BAMM models, as the model's namespaces need to be adjusted, which effectively is the same as migrating the model. 

Would be great if the SAMM SDK could process outdated BAMM models for a while, to allow a smooth migration procedure.

### PR DESCRIPTION
**Pull request by RaMisess**
Fixes #363

### CODE REVIEW

File: core/esmf-aspect-meta-model-version-migrator/src/main/java/org/eclipse/esmf/aspectmodel/versionupdate/migrator/BammUriRewriter.java
Comment (atextor) [inline core/esmf-aspect-meta-model-version-migrator/src/main/java/org/eclipse/esmf/aspectmodel/versionupdate/migrator/BammUriRewriter.java:1]: Please also adapt the unit test: Add a BammTest.ttl for BAMM 1.0.0 as well (BammTest for BAMM 2.0.0 already exists) and make AspectModelResolverTest#testLoadLegacyBammModelExpectSuccess a ParameterizedTest (with allVersions)

**Review by atextor — CHANGES_REQUESTED** [review]

File: core/esmf-aspect-model-resolver/src/test/resources/samm_2_0_0/org.eclipse.esmf.test/1.0.0/BammTest.ttl [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+@prefix bamm:   <urn:bamm:io.openmanufacturing:meta-model:1.0.0#> .
+@prefix bamm-c: <urn:bamm:io.openmanufacturing:characteristic:1.0.0#> .
+@prefix bamm-e: <urn:bamm:io.openmanufacturing:entity:1.0.0#> .
+@prefix :       <urn:bamm:org.eclipse.esmf.test:2.0.0#> .
+@prefix unit:   <urn:bamm:io.openmanufacturing:unit:1.0.0#> .
+@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
+
+:BammTest a bamm:Aspect ;
+   bamm:preferredName "BAMM Test"@en ;
```
Comment (atextor) [inline core/esmf-aspect-model-resolver/src/test/resources/samm_2_0_0/org.eclipse.esmf.test/1.0.0/BammTest.ttl:20]: To make this a valid BAMM 1.0.0 model, `bamm:name` is required on all element

**Review by atextor — CHANGES_REQUESTED** [review]

File: core/esmf-aspect-model-resolver/src/test/resources/samm_1_0_0/org.eclipse.esmf.test/2.0.0/BammTest.ttl [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+@prefix unit:   <urn:bamm:io.openmanufacturing:unit:1.0.0#> .
+@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
+
+:BammTest a bamm:Aspect ;
+   bamm:name "BammTest" ;
+   bamm:preferredName "BAMM Test"@en ;
+   bamm:properties ( :property ) ;
+   bamm:operations ( ) .
+
+:property a bamm:Property ;
```
Comment (atextor) [inline core/esmf-aspect-model-resolver/src/test/resources/samm_1_0_0/org.eclipse.esmf.test/2.0.0/BammTest.ttl:25]: The property also needs a `bamm:name`

**Review by atextor — CHANGES_REQUESTED** [review]

File: core/esmf-aspect-model-resolver/src/test/resources/samm_1_0_0/org.eclipse.esmf.test/2.0.0/BammTest.ttl [hunk 3]
```diff
@@ -23,4 +23,5 @@
    bamm:operations ( ) .
 
 :property a bamm:Property ;
+   bamm:name "TestProperty" ;
```
Comment (atextor) [inline core/esmf-aspect-model-resolver/src/test/resources/samm_1_0_0/org.eclipse.esmf.test/2.0.0/BammTest.ttl:26]: The value of `bamm:name` must be identical to the URN's local part, i.e. in this case "property".

**Review by atextor — CHANGES_REQUESTED** [review]

File: core/esmf-aspect-model-resolver/src/test/resources/samm_1_0_0/org.eclipse.esmf.test/2.0.0/BammTest.ttl [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
+
+:BammTest a bamm:Aspect ;
+   bamm:name "BammTest" ;
+   bamm:preferredName "BAMM Test"@en ;
+   bamm:properties ( :property ) ;
+   bamm:operations ( ) .
+
+:property a bamm:Property ;
+   bamm:name "TestProperty" ;
```
Comment (atextor) [inline core/esmf-aspect-model-resolver/src/test/resources/samm_1_0_0/org.eclipse.esmf.test/2.0.0/BammTest.ttl]: The value of `bamm:name` must be identical to the URN's local part, i.e. in this case "property".

```suggestion
   bamm:name "property" ;
```

**Review by atextor — CHANGES_REQUESTED** [review]

**Review by atextor — APPROVED** [review]
