### PR TITLE
Fix wrong documentation URL in the detailed validation message

### LINKED ISSUE #880: [BUG] The `aspect validate` command shows a wrong documentation link
**How: List of performed steps**

Run the `aspect validate` command against invalid models with the `--details` option. For example:

```
$ curl -sLO https://github.com/eclipse-esmf/esmf-sdk/releases/download/v2.13.1/samm-cli-2.13.1.jar
$ java -jar samm-cli-2.13.1.jar aspect https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.pcf/4.0.0/Pcf.ttl validate --details
```

**What: Actual result vs expected result**

The actual output above is as follows:

```
# Validation errors were found:

- violation-type: ProcessingViolation
  error-code: ERR_PROCESSING
  description: Repository does not contain any file that contains the element definition (GitHub repository eclipse-tractusx/sldt-semantic-models (branch main, directory /))
 documentation: https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/error-codes.htmlerr-processing  could-not-resolve: Optional[urn:samm:io.catenax.pcf:4.0.0#Pcf]
    - checked-location: GitHub repository eclipse-tractusx/sldt-semantic-models (branch main, directory /)
    - reason: Repository does not contain any file that contains the element definition
```

But the documentation URL should be https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/error-codes.html#ERR-PROCESSING.

**Where: (e.g. component, version, url, your system info)**

My system info is as follow:

```
$ arch
x86_64
$ cat /etc/issue
Ubuntu 24.04.3 LTS \n \l

$ java -version
openjdk version "25.0.1" 2025-10-21 LTS
OpenJDK Runtime Environment Corretto-25.0.1.8.1 (build 25.0.1+8-LTS)
OpenJDK 64-Bit Server VM Corretto-25.0.1.8.1 (build 25.0.1+8-LTS, mixed mode, sharing)
```

**Input (files/screenshots)**

**Output (files/screenshots)**

**Additional context (e.g. references)**

### PR DESCRIPTION
**Pull request by sekikn**
## Description

This PR fixes a wrong link in the error message shown by `aspect validate --details`.

Fixes #880 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
  - these two are not necessary since it's just a minor fix
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/validation/services/DetailedViolationFormatter.java [hunk 1]
```diff
@@ -143,8 +143,8 @@ private String formatViolation( final Violation violation, final Supplier<String
          }
       }
       // Add documentation link
-      builder.append( " documentation: https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/error-codes.html"
-            + violation.errorCode().toLowerCase().replace( "_", "-" ) );
+      builder.append( "  documentation: https://eclipse-esmf.github.io/esmf-developer-guide/tooling-guide/error-codes.html#"
+            + violation.errorCode().toUpperCase().replace( "_", "-" ) );
```
Comment (atextor) [inline core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/validation/services/DetailedViolationFormatter.java]: Please make `ERROR_CODES_DOC_LINK` in `ViolationFormatter` protected, and use it here:

```suggestion
      builder.append( "  documentation: " + ERROR_CODES_DOC_LINK
            + violation.errorCode().toUpperCase().replace( "_", "-" ) );
```

Comment (sekikn) [reply core/esmf-aspect-model-validator/src/main/java/org/eclipse/esmf/aspectmodel/validation/services/DetailedViolationFormatter.java]: @atextor Thanks for the comment! I've just updated the PR.
