### PR TITLE
Fix AspectModelLoader throws NullPointerException

### LINKED ISSUE #652: [BUG] AspectModelLoader throws NullPointerException
**How: List of performed steps**
- load an invalid model using AspectModelLoader

**What: Actual result vs expected result**
- actual: loader fails with NullPointerException with message Cannot invoke "org.apache.jena.rdf.model.Statement.getObject()" because "dataType" is null
- expected: other exception describing the actual problem

**Where: (e.g. component, version, url, your system info)**
org.eclipse.esmf:esmf-aspect-meta-model-java:2.9.5

**Additional context (e.g. references)**
[org.example.validation.test.zip](https://github.com/user-attachments/files/16895191/org.example.validation.test.zip)
- run test ValidationTest
- in SDK 2.7.0 there was a chance to validate: the model was loaded, resolved and then validated. The validation message was
 [No datatype is defined on the Characteristic instance ':Characteristic1'.]

### PR DESCRIPTION
**Pull request by Yauhenikapl**
## Description

Fix AspectModelLoader throws NullPointerException by adding another message and exception type

Fixes #652 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: core/esmf-aspect-meta-model-java/src/main/java/org/eclipse/esmf/aspectmodel/loader/Instantiator.java [hunk 1]
```diff
@@ -116,7 +116,14 @@ protected Type getType( final Resource characteristicResource ) {
    private Statement getDataType( final Resource resource ) {
       return Optional.ofNullable( resource.getPropertyResourceValue( SammNs.SAMMC.baseCharacteristic() ) )
             .map( this::getDataType )
-            .orElseGet( () -> resource.getProperty( SammNs.SAMM.dataType() ) );
+            .orElseGet( () -> {
+               final Statement dataType = resource.getProperty( SammNs.SAMM.dataType() );
+               if ( dataType == null ) {
+                  throw new IllegalStateException(
```
Comment (atextor) [inline core/esmf-aspect-meta-model-java/src/main/java/org/eclipse/esmf/aspectmodel/loader/Instantiator.java:122]: The only exception that should be thrown by the Instantiators is `AspectLoadingException`.

File: core/esmf-aspect-meta-model-java/src/test/resources/samm_2_1_0/invalid_characteristic_datatype.ttl
Comment (atextor) [inline core/esmf-aspect-meta-model-java/src/test/resources/samm_2_1_0/invalid_characteristic_datatype.ttl:1]: Test models such as this should be part of the `esmf-test-aspect-models` module, in the "invalid" folder. Accordingly, the `org.eclipse.esmf.test.InvalidTestAspect` enumeration should be complemented. The file name needs to be in UpperCamelCase.

**Review by atextor — CHANGES_REQUESTED** [review]

**Review by atextor — APPROVED** [review]
